import {readFile,writeFile,mkdir} from 'node:fs/promises';
const root=new URL('../',import.meta.url);
const h=JSON.parse(await readFile(new URL('data/history.json',root),'utf8'));
const Z={horse:[1,13,25,37,49],snake:[2,14,26,38],dragon:[3,15,27,39],rabbit:[4,16,28,40],tiger:[5,17,29,41],ox:[6,18,30,42],mouse:[7,19,31,43],pig:[8,20,32,44],dog:[9,21,33,45],rooster:[10,22,34,46],monkey:[11,23,35,47],goat:[12,24,36,48]};
const CN={horse:'马',snake:'蛇',dragon:'龙',rabbit:'兔',tiger:'虎',ox:'牛',mouse:'鼠',pig:'猪',dog:'狗',rooster:'鸡',monkey:'猴',goat:'羊'};
const fifth=h.draws.filter(d=>d.issue>='26/047'&&d.issue<='26/999').sort((a,b)=>a.issue.localeCompare(b.issue));
const esc=s=>String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const shell=(title,desc,body)=>`<!doctype html><html lang="zh-Hans"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(desc)}"><meta name="robots" content="index,follow"><link rel="stylesheet" href="../../styles.css?v=3.0.1"></head><body><div class="app-shell"><header class="topbar"><div><div class="brand">六合彩数据中心</div><div class="subtitle">Mark Six Data Hub · 历史数据统计</div></div></header><main>${body}<p class="fineprint"><a href="../../">返回数据中心</a> · 历史统计不代表未来开奖概率。</p></main></div></body></html>`;
async function put(path,html){const u=new URL(path,root);await mkdir(new URL('./',u),{recursive:true});await writeFile(u,html)}
for(const d of fifth){const slug=d.issue.replace('/','-');await put(`draw/${slug}/index.html`,shell(`${d.issue}期开奖结果｜六合彩数据中心`,`${d.date} ${d.issue}期开奖结果与号码资料。`,`<section class="hero card"><div class="hero-kicker">开奖记录</div><h1>${d.issue}</h1><p>${d.date}</p></section><div class="section-head"><h2>开奖号码</h2></div><div class="card explanation"><h3>${d.main.map(n=>String(n).padStart(2,'0')).join(' · ')} + ${String(d.special).padStart(2,'0')}</h3><p>正选6个号码；特别号：<b>${String(d.special).padStart(2,'0')}</b></p></div>`))}
for(let n=1;n<=49;n++){const mains=fifth.filter(d=>d.main.includes(n)),special=fifth.filter(d=>d.special===n),z=Object.keys(Z).find(k=>Z[k].includes(n));await put(`number/${String(n).padStart(2,'0')}/index.html`,shell(`${String(n).padStart(2,'0')}号历史数据｜六合彩号码统计`,`${String(n).padStart(2,'0')}号第五代搅珠机正选、特别号历史统计。`,`<section class="hero card"><div class="hero-kicker">号码数据库</div><h1>${String(n).padStart(2,'0')}号 · ${CN[z]}</h1><p>第五代搅珠机样本</p></section><div class="metric-grid"><div class="metric card"><span>正选出现</span><strong>${mains.length}次</strong></div><div class="metric card"><span>特别号出现</span><strong>${special.length}次</strong></div></div><div class="card explanation"><h3>最近记录</h3><p>${[...fifth].reverse().filter(d=>d.main.includes(n)||d.special===n).slice(0,10).map(d=>d.issue+' · '+d.date+(d.special===n?' · 特别号':'')).join('<br>')||'暂无'}</p></div>`))}
for(const [k,nums] of Object.entries(Z)){const hits=fifth.filter(d=>nums.some(n=>[...d.main,d.special].includes(n))),r=fifth.slice(-10).filter(d=>nums.some(n=>[...d.main,d.special].includes(n))).length;await put(`zodiac/${k}/index.html`,shell(`${CN[k]}生肖数据｜六合彩生肖统计`,`${CN[k]}生肖第五代搅珠机累计命中与最近10期统计。`,`<section class="hero card"><div class="hero-kicker">生肖数据库</div><h1>${CN[k]}生肖</h1><p>${nums.map(n=>String(n).padStart(2,'0')).join(' · ')}</p></section><div class="metric-grid"><div class="metric card"><span>累计命中</span><strong>${hits.length}/${fifth.length}</strong></div><div class="metric card"><span>最近10期</span><strong>${r}/10</strong></div></div>`))}
await put('special/index.html',shell('特别号数据库｜六合彩数据中心','第五代搅珠机特别号独立历史统计。',`<section class="hero card"><div class="hero-kicker">独立统计</div><h1>特别号数据库</h1><p>每期1个特别号，与6个正选分开统计。</p></section><div class="card explanation"><h3>01–49特别号累计次数</h3><p>${Array.from({length:49},(_,i)=>{const n=i+1;return String(n).padStart(2,'0')+'：'+fifth.filter(d=>d.special===n).length+'次'}).join('<br>')}</p></div>`));
await put('machine/5th-gen/index.html',shell('第五代搅珠机数据｜六合彩数据中心','2026年5月5日起第五代搅珠机独立样本统计。',`<section class="hero card"><div class="hero-kicker">机器专题</div><h1>第五代搅珠机</h1><p>自2026-05-05（26/047）起独立统计。</p></section><div class="metric-grid"><div class="metric card"><span>当前样本</span><strong>${fifth.length}期</strong></div><div class="metric card"><span>最新期号</span><strong>${fifth.at(-1)?.issue}</strong></div></div><div class="card explanation"><h3>统计原则</h3><p>正选、特别号与生肖分别统计；历史异常仅描述样本，不证明机器偏差，也不代表未来概率。</p></div>`));
const base='https://king8899vip-a11y.github.io/marksix-analyzer';
const urls=['/',...fifth.map(d=>'/draw/'+d.issue.replace('/','-')+'/'),...Array.from({length:49},(_,i)=>'/number/'+String(i+1).padStart(2,'0')+'/'),...Object.keys(Z).map(k=>'/zodiac/'+k+'/'),'/special/','/machine/5th-gen/'];
await writeFile(new URL('sitemap.xml',root),'<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+urls.map(u=>`<url><loc>${base}${u}</loc></url>`).join('\n')+'\n</urlset>\n');
await writeFile(new URL('robots.txt',root),`User-agent: *\nAllow: /\nSitemap: ${base}/sitemap.xml\n`);
console.log(`Generated V3 SEO pages: ${urls.length}`);
